### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by meteosismi** [W3PM/40MHz-GPS-FT8-WSPR-MEPT#1]
Hi Gene. I have a problem. After 2 trasmission of wspr or 1 trasmission of ft8 the system stop working. Gps work well and on display remain last lat and lon before trasmitting last data ... How i resolve this problem? Thank you and 73.

**Comment by W3PM** [comment]
If you forward a copy of your .ino sketch to w3pm_at_amsat_dot_org I will look at it and try to determine where the problem is.
